- name: Update Cache if older than 1h
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: install stunnel4 dependency
  ansible.builtin.apt:
    name: "stunnel4"
    install_recommends: no
    state: present
  become: yes

- name: Install the mlat package from github
  ansible.builtin.apt:
    deb: "{{ adsb_mlat_deb_url }}"
    state: present
  become: yes
